// Agent-maker (Phase 14 meta layer, docs/company-vision.md). A meta-agent that
// DRAFTS new roster entries — it never adds them. The roster in agents.js is one
// source of truth that regenerates plugin/agents/*.md; changing it is a
// self-upgrade to Raphael's own code, so it goes through a human: branch + tests +
// eval + regenerate (the self-upgrade rule). This module just produces a validated
// PROPOSAL (the roster literal to paste + the generated agent markdown to preview)
// and a demand signal to justify one. Demand-driven only — no speculative agents.

import path from 'node:path';
import { AGENTS, renderAgent } from './agents.js';
import { atomicWrite } from './files.js';
import { p } from './paths.js';

const MODELS = new Set(['haiku', 'sonnet', 'opus', 'inherit']);
const DEFAULT_TOOLS = ['Read', 'Grep', 'Glob'];
const SLUG_RE = /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/;

// Validate + normalise a proposed roster entry. Returns { ok, errors, entry }.
export function validateAgentProposal(spec = {}, { roster = AGENTS } = {}) {
  const errors = [];
  const slug = String(spec.slug ?? '').trim();
  if (!SLUG_RE.test(slug)) errors.push('E-AGENT: slug must be kebab-case (a-z, 0-9, hyphens)');
  if (roster.some((a) => a.slug === slug)) errors.push(`E-AGENT: slug "${slug}" already exists in the roster`);
  const role = String(spec.role ?? '').trim();
  if (role.length < 10) errors.push('E-AGENT: --role must describe the specialist (>=10 chars)');
  const mission = String(spec.mission ?? '').trim();
  if (mission.length < 20) errors.push('E-AGENT: --mission must be a real brief (>=20 chars)');
  const output = String(spec.output ?? '').trim();
  if (output.length < 10) errors.push('E-AGENT: --output must say what the agent returns (>=10 chars)');
  const model = String(spec.model ?? 'inherit').trim();
  if (!MODELS.has(model)) errors.push(`E-AGENT: model must be one of ${[...MODELS].join(', ')}`);
  // Every agent needs a whenToUse trigger — it is what Claude Code matches against to
  // auto-delegate (agent-architecture-final.md; the flagship tier was retired).
  const whenToUse = String(spec.whenToUse ?? '').trim();
  if (whenToUse.length < 10) errors.push('E-AGENT: --when-to-use must name the situations that should invoke this agent (>=10 chars)');

  const tools = Array.isArray(spec.tools) && spec.tools.length ? spec.tools.map((t) => String(t).trim()).filter(Boolean) : DEFAULT_TOOLS;

  const entry = { slug, name: spec.name?.trim() || titleCase(slug), model, tools, role, whenToUse, mission, output };
  return { ok: errors.length === 0, errors, entry };
}

function titleCase(slug) {
  return slug.split('-').map((s) => s.charAt(0).toUpperCase() + s.slice(1)).join(' ');
}

// The roster literal to paste into agents.js AGENTS (a human edit — never done here).
export function rosterSnippet(entry) {
  const toolList = entry.tools.map((t) => `'${t}'`).join(', ');
  return [
    '  {',
    `    slug: '${entry.slug}',`,
    `    name: ${JSON.stringify(entry.name)},`,
    `    model: '${entry.model}',`,
    `    tools: [${toolList}],`,
    `    role: ${JSON.stringify(entry.role)},`,
    `    whenToUse: ${JSON.stringify(entry.whenToUse)},`,
    `    mission: ${JSON.stringify(entry.mission)},`,
    `    output: ${JSON.stringify(entry.output)}`,
    '  },'
  ].join('\n');
}

// A PROPOSAL: the validated entry + a preview of the generated agent markdown
// (renderAgent, the real generator) with an unmistakable banner + the paste snippet.
export function proposeAgentDraft(entry) {
  const banner = [
    '<!-- PROPOSAL — generated by raph agent propose. NOT installed. -->',
    '<!-- To adopt: add the roster snippet below to src/lib/agents.js AGENTS, then -->',
    '<!-- run scripts/build-agents.mjs, npm test, and raph eval before committing. -->',
    ''
  ].join('\n');
  const snippet = ['', '<!-- Roster snippet for src/lib/agents.js:', rosterSnippet(entry), '-->', ''].join('\n');
  return `${banner}${renderAgent(entry)}${snippet}`;
}

export function writeAgentProposal(entry) {
  const file = path.join(p.home(), 'staged', 'agents', `${entry.slug}.md`);
  atomicWrite(file, proposeAgentDraft(entry));
  return { path: file, slug: entry.slug };
}

// Demand signal: active lessons per category vs the current roster. Agent creation
// should be justified by unmet demand (a domain the brain has learned a lot about
// but no specialist owns), not invented. Informational — the human decides.
export function agentDemand(lessons = [], { roster = AGENTS } = {}) {
  const byCategory = new Map();
  for (const l of lessons) byCategory.set(l.category, (byCategory.get(l.category) || 0) + 1);
  const categories = [...byCategory.entries()].map(([category, count]) => ({ category, lessons: count })).sort((a, b) => b.lessons - a.lessons);
  return { categories, roster: roster.map((a) => a.slug), lessonCount: lessons.length };
}

export function renderDemand(d) {
  const L = [];
  L.push(`raph agent demand — ${d.lessonCount} active lesson(s) across ${d.categories.length} categor(ies)`);
  L.push(`  roster (${d.roster.length}): ${d.roster.join(', ')}`);
  L.push('');
  for (const c of d.categories) L.push(`  ${c.category}: ${c.lessons} lesson(s)`);
  L.push('');
  L.push('A new agent should be justified by a category the brain has learned a lot about');
  L.push('but no current specialist owns. Draft one: raph agent propose <slug> --role … --mission … --output …');
  return L.join('\n');
}
