// Skills factory (docs/company-vision.md). Raphael watching
// its OWN recall to notice when a lesson has graduated from "a note worth recalling"
// to "a recurring need worth packaging" — a lesson that fires across many sessions is
// a candidate to become a reusable SKILL. Like adopt's skill drafts, output is STAGED,
// branded DRAFT, and NEVER auto-installed (installing a skill = handing agents
// instructions; that stays a human act). Pure detection + pure rendering + a thin
// disk writer. Zero model tokens: the signal is deterministic self-observation.

import path from 'node:path';
import { atomicWrite } from './files.js';
import { scrubSecrets } from './scrub.js';
import { p } from './paths.js';

const MIN_INJECTIONS = 20; // need real recall history before "fires broadly" means anything
const MIN_SESSIONS = 5;    // fired across >=5 distinct sessions = a recurring need

// From the injection log, how many DISTINCT sessions each lesson fired in.
export function sessionsPerLesson(events = []) {
  const injected = events.filter((e) => e.event === 'injected');
  const map = new Map(); // id -> Set(session_id)
  for (const e of injected) {
    const sid = e.session_id || 'unknown';
    for (const l of e.lessons ?? []) {
      if (!map.has(l.id)) map.set(l.id, new Set());
      map.get(l.id).add(sid);
    }
  }
  return map;
}

// Lessons that fire broadly enough to be worth packaging as a skill. Gated on
// enough recall history for "broad" to be meaningful (capability-check). Returns
// { ready, reason, items }.
export function skillCandidates(lessons, { events = [], now = new Date() } = {}) {
  const injected = events.filter((e) => e.event === 'injected');
  if (injected.length < MIN_INJECTIONS) {
    return { ready: false, reason: `only ${injected.length} injection(s) — need ${MIN_INJECTIONS} before "fires broadly" is meaningful`, items: [] };
  }
  const perLesson = sessionsPerLesson(events);
  const items = [];
  for (const l of lessons) {
    const sessions = perLesson.get(l.id)?.size ?? 0;
    if (sessions < MIN_SESSIONS) continue;
    items.push({ id: l.id, slug: l.slug, category: l.category, sessions, why: `fired across ${sessions} distinct sessions — a recurring need` });
  }
  items.sort((a, b) => b.sessions - a.sessions || a.slug.localeCompare(b.slug));
  return { ready: true, items };
}

// Render a SKILL.md draft from a lesson. The "Honest limits" section is MANDATORY
// (the fable-skills handover rule): a generated skill must state what it does NOT
// guarantee. Secrets scrubbed on output; branded DRAFT; status: draft.
export function renderSkillDraft(lesson) {
  const slug = lesson.slug;
  const desc = lesson.injection?.headline || lesson.title || slug;
  const guidance = scrubSecrets(String(lesson.lesson ?? '')).text;
  const kws = lesson.triggers?.keywords ?? [];
  const paths = lesson.triggers?.paths ?? [];

  const whenLines = [];
  if (kws.length) whenLines.push(`- When the work touches: ${kws.join(', ')}.`);
  if (paths.length) whenLines.push(`- When editing paths like: ${paths.join(', ')}.`);
  if (!whenLines.length) whenLines.push('- When the situation below recurs in your work.');

  const limits = [
    '- This skill was distilled from past-session evidence; it can be wrong, narrow, or out of date.',
    '- It carries no authority to act — it is advice, not a command. Verify before relying on it.'
  ];
  if (lesson.counter_indications) limits.push(`- Does NOT apply when: ${scrubSecrets(String(lesson.counter_indications)).text}`);
  if ((lesson.evidence?.distinct_projects ?? 0) < 2) limits.push('- Seen in only one project so far — may not generalise.');

  const front = [
    '---',
    `name: ${slug}`,
    `description: ${JSON.stringify(desc)}`,
    'status: draft',
    `distilled_from: ${lesson.id}`,
    `category: ${lesson.category}`,
    `tier: ${lesson.provenance?.tier ?? 'auto'}`,
    '---',
    '',
    '> DRAFT generated by Raphael\'s skills factory from a lesson that fires broadly.',
    '> Review before installing — installing a skill hands agents instructions.',
    ''
  ].join('\n');

  return `${front}## When to use\n${whenLines.join('\n')}\n\n## Guidance\n${guidance}\n\n## Honest limits\n${limits.join('\n')}\n`;
}

// Write a draft to the staged skills area (NOT installed). Returns { path, slug }.
export function draftSkillFromLesson(lesson) {
  const slug = lesson.slug;
  const file = path.join(p.skillDrafts(), slug, 'SKILL.md');
  atomicWrite(file, renderSkillDraft(lesson));
  return { path: file, slug };
}

export function renderSkillSuggestions(result) {
  const L = [];
  if (!result.ready) {
    return `raph skills — ${result.reason}\n  (skill suggestions need recall history; approve lessons + use the agent, then check back)`;
  }
  L.push(`raph skills — ${result.items.length} lesson(s) fire broadly enough to package as a skill`);
  if (!result.items.length) {
    L.push('  none yet — no active lesson has fired across enough sessions.');
    return L.join('\n');
  }
  L.push('');
  for (const it of result.items) {
    L.push(`  ${it.slug}  [${it.category}]  — ${it.why}`);
  }
  L.push('');
  L.push('Draft one (staged, NOT installed): raph skills draft <slug>. Review before installing.');
  return L.join('\n');
}

// 18.7 — description-quality lint for SKILL.md drafts.
//
// A skill's `description` is its ROUTER: the host matches against it to decide
// whether to load the skill at all. Two ways that fails, and they are opposites:
// too GENERIC and it fires on everything (noise, wasted context on every task);
// too NARROW and it never fires (dead weight nobody notices). Both are cheap to
// spot deterministically, and neither shows up as an error anywhere else.
const VAGUE_WORDS = ['helper', 'utility', 'various', 'stuff', 'things', 'general', 'misc', 'assorted'];

export function lintSkillDescription(description, { name = '' } = {}) {
  const desc = String(description ?? '').trim();
  const issues = [];
  const words = desc.split(/\s+/).filter(Boolean);

  if (!desc) {
    issues.push({ level: 'error', code: 'SKILL-DESC-MISSING', msg: 'no description — the host has nothing to match on, so the skill can never fire' });
    return issues;
  }
  if (words.length < 6) {
    issues.push({ level: 'warn', code: 'SKILL-DESC-THIN', msg: `only ${words.length} word(s) — too thin to route on; name the situation that should trigger it` });
  }
  if (words.length > 60) {
    issues.push({ level: 'warn', code: 'SKILL-DESC-BLOATED', msg: `${words.length} words — a description this long dilutes the match and costs context on every load` });
  }
  const vague = VAGUE_WORDS.filter((w) => new RegExp(`\\b${w}\\b`, 'i').test(desc));
  if (vague.length) {
    issues.push({ level: 'warn', code: 'SKILL-DESC-VAGUE', msg: `vague wording (${vague.join(', ')}) makes it match almost any task — say what it is FOR` });
  }
  // A description that never names a trigger situation tends to never fire.
  if (!/\b(use|when|for|before|after|if)\b/i.test(desc)) {
    issues.push({ level: 'warn', code: 'SKILL-DESC-NO-TRIGGER', msg: 'names no situation ("use when…") — the host has no cue for when to load it' });
  }
  if (name && desc.toLowerCase().trim() === String(name).toLowerCase().replace(/-/g, ' ').trim()) {
    issues.push({ level: 'warn', code: 'SKILL-DESC-ECHO', msg: 'the description just restates the name and adds no routing signal' });
  }
  return issues;
}
