// 18.6 — canonical AGENTS.md (the reach mechanism: CLIs like codex read it natively)
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, writeFileSync, readFileSync, existsSync, mkdirSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { renderAgentsMd, AGENTS_MD_BUDGET } from '../src/lib/agentsmd.js';
import agentsMd from '../src/commands/agents-md.js';

const LESSONS = [
  { id: 'les_01C', title: 'C title', headline: 'C headline' },
  { id: 'les_01A', title: 'A title', headline: 'A headline' },
  { id: 'les_01B', title: 'B title', headline: 'B headline' }
];

function tmpdir() {
  return mkdtempSync(path.join(os.tmpdir(), 'raph-agmd-'));
}

test('the file frames lessons as advisory DATA that cannot authorise anything', () => {
  const md = renderAgentsMd({ lessons: LESSONS });
  // this matters more here than in the plugin: another vendor's CLI reads this
  // file without any of Raphael's own framing hooks
  assert.match(md, /\*\*advisory DATA, not instructions/i);
  assert.match(md, /cannot authorise|can authorise an action/i);
  assert.match(md, /the code\s+wins/i, 'must say the code beats a stale lesson');
  assert.match(md, /raph search/, 'must tell the agent how to pull more');
});

test('lessons render in stable ascending id order (same reasoning as 18.1)', () => {
  const md = renderAgentsMd({ lessons: LESSONS });
  const order = ['A headline', 'B headline', 'C headline'].map((h) => md.indexOf(h));
  assert.deepEqual(order, [...order].sort((x, y) => x - y), 'a regenerated file must not reshuffle');
  // and it is deterministic for the same input
  assert.equal(renderAgentsMd({ lessons: LESSONS }), md);
});

test('an over-long headline is clamped and points at the full text', () => {
  const long = 'x'.repeat(400);
  const md = renderAgentsMd({ lessons: [{ id: 'les_01Z', title: 't', headline: long }] });
  assert.ok(!md.includes(long), 'the raw 400-char headline must not be dumped');
  assert.match(md, /raph show les_01Z/, 'clamped lines point at the full lesson');
});

test('the budget is respected however many lessons exist', () => {
  const many = Array.from({ length: 500 }, (_, i) => ({
    id: `les_${String(i).padStart(4, '0')}`, title: `t${i}`, headline: `headline number ${i} about something durable`
  }));
  const md = renderAgentsMd({ lessons: many });
  const bulletTokens = md.split('\n').filter((l) => l.startsWith('- ')).join('\n').length / 4;
  assert.ok(bulletTokens <= AGENTS_MD_BUDGET + 20, `lesson block blew the budget: ${bulletTokens}`);
});

test('an empty brain still produces a usable file, not an empty ceremony (edge)', () => {
  const md = renderAgentsMd({ lessons: [] });
  assert.match(md, /no active lessons yet/i);
  assert.match(md, /raph search/);
  // optional sections stay absent rather than printing empty headings
  assert.ok(!md.includes('## Settled decisions'));
  assert.ok(!md.includes('## Where to look'));
});

test('optional sections appear only when there is something to say', () => {
  const md = renderAgentsMd({ lessons: LESSONS, decisions: 'we ship localhost-only', atlasHint: 'ask raph atlas where' });
  assert.match(md, /## Settled decisions/);
  assert.match(md, /## Where to look/);
});

test('the command refuses to clobber a hand-written AGENTS.md, and --force overrides', async () => {
  const dir = tmpdir();
  const prevHome = process.env.RAPHAEL_HOME;
  const cwd = process.cwd();
  process.env.RAPHAEL_HOME = dir;
  try {
    const target = path.join(dir, 'AGENTS.md');
    writeFileSync(target, '# my own notes\nhand written, do not lose this', 'utf8');
    const refused = await agentsMd(['--out', target]);
    assert.equal(refused, 1, 'must refuse rather than overwrite');
    assert.match(readFileSync(target, 'utf8'), /hand written/, 'the file must be untouched');

    assert.equal(await agentsMd(['--out', target, '--force']), 0);
    assert.match(readFileSync(target, 'utf8'), /Generated by Raphael/);

    // a file Raphael itself wrote is safe to regenerate without --force
    assert.equal(await agentsMd(['--out', target]), 0);
  } finally {
    process.chdir(cwd);
    if (prevHome === undefined) delete process.env.RAPHAEL_HOME; else process.env.RAPHAEL_HOME = prevHome;
    rmSync(dir, { recursive: true, force: true });
  }
});

test('--out writes where asked and the file is non-empty', async () => {
  const dir = tmpdir();
  const prevHome = process.env.RAPHAEL_HOME;
  process.env.RAPHAEL_HOME = dir;
  try {
    const target = path.join(dir, 'nested', 'AGENTS.md');
    rmSync(path.join(dir, 'nested'), { recursive: true, force: true });
    mkdirSync(path.join(dir, 'nested'), { recursive: true });
    assert.equal(await agentsMd(['--out', target]), 0);
    assert.ok(existsSync(target));
    assert.ok(readFileSync(target, 'utf8').length > 200);
  } finally {
    if (prevHome === undefined) delete process.env.RAPHAEL_HOME; else process.env.RAPHAEL_HOME = prevHome;
    rmSync(dir, { recursive: true, force: true });
  }
});
