import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, existsSync, readFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { skillCandidates, sessionsPerLesson, renderSkillDraft, draftSkillFromLesson } from '../src/lib/skillfactory.js';
import { p } from '../src/lib/paths.js';

function lesson(over = {}) {
  return {
    id: over.id ?? 'les_1',
    slug: over.slug ?? 'validate-boundary',
    title: over.title ?? 'Validate input at the boundary',
    category: over.category ?? 'correctness',
    lesson: over.lesson ?? 'Validate every external input at the trust boundary before use.',
    counter_indications: over.counter_indications,
    triggers: over.triggers ?? { keywords: ['validate', 'input'], paths: ['src/api/**'] },
    evidence: over.evidence ?? { distinct_projects: 3 },
    injection: over.injection ?? { headline: 'Unvalidated input reached the DB layer.' },
    provenance: over.provenance ?? { tier: 'user' }
  };
}

// N injected events, `fires` of them (each a distinct session) include the lesson id.
function events(id, fires, total = 25) {
  return Array.from({ length: total }, (_, i) => ({
    event: 'injected',
    session_id: `s${i}`,
    lessons: i < fires ? [{ id }] : []
  }));
}

test('sessionsPerLesson counts distinct sessions a lesson fired in', () => {
  const ev = [
    { event: 'injected', session_id: 'a', lessons: [{ id: 'x' }] },
    { event: 'injected', session_id: 'a', lessons: [{ id: 'x' }] }, // same session
    { event: 'injected', session_id: 'b', lessons: [{ id: 'x' }] },
    { event: 'approved', session_id: 'c', id: 'x' } // not an injection
  ];
  assert.equal(sessionsPerLesson(ev).get('x').size, 2);
});

test('skillCandidates needs injection history before judging', () => {
  const r = skillCandidates([lesson()], { events: events('les_1', 3, 5) }); // only 5 injections
  assert.equal(r.ready, false);
  assert.equal(r.items.length, 0);
});

test('skillCandidates flags a lesson firing across >=5 sessions', () => {
  const broad = lesson({ id: 'les_broad', slug: 'broad-one' });
  const narrow = lesson({ id: 'les_narrow', slug: 'narrow-one' });
  const ev = [...events('les_broad', 6), ...events('les_narrow', 2)];
  const r = skillCandidates([broad, narrow], { events: ev });
  assert.equal(r.ready, true);
  assert.deepEqual(r.items.map((i) => i.slug), ['broad-one']);
  assert.equal(r.items[0].sessions, 6);
});

test('renderSkillDraft has when-to-use, guidance, and a MANDATORY honest-limits section', () => {
  const md = renderSkillDraft(lesson({ counter_indications: 'the input is already schema-validated upstream' }));
  assert.match(md, /status: draft/);
  assert.match(md, /distilled_from: les_1/);
  assert.match(md, /## When to use/);
  assert.match(md, /validate, input/);
  assert.match(md, /## Guidance/);
  assert.match(md, /## Honest limits/);
  assert.match(md, /no authority to act/);
  assert.match(md, /Does NOT apply when: the input is already schema-validated/);
  assert.match(md, /DRAFT generated by Raphael/);
});

test('single-project lessons get a does-not-generalise limit', () => {
  const md = renderSkillDraft(lesson({ evidence: { distinct_projects: 1 } }));
  assert.match(md, /only one project/);
});

test('secrets in a lesson body are scrubbed out of the draft', () => {
  const md = renderSkillDraft(lesson({ lesson: 'Never hardcode AKIAIOSFODNN7EXAMPLE; load it from the environment at startup instead.' }));
  assert.ok(!md.includes('AKIAIOSFODNN7EXAMPLE'));
  assert.match(md, /<SECRET:/);
});

test('draftSkillFromLesson writes a staged SKILL.md (not installed)', () => {
  const dir = mkdtempSync(path.join(os.tmpdir(), 'raph-skf-'));
  const prev = process.env.RAPHAEL_HOME;
  process.env.RAPHAEL_HOME = dir;
  try {
    const { path: file, slug } = draftSkillFromLesson(lesson({ slug: 'my-skill' }));
    assert.equal(slug, 'my-skill');
    assert.ok(existsSync(file));
    assert.ok(file.includes(path.join('staged', 'skills', 'my-skill')));
    assert.match(readFileSync(file, 'utf8'), /## Honest limits/);
  } finally {
    if (prev === undefined) delete process.env.RAPHAEL_HOME;
    else process.env.RAPHAEL_HOME = prev;
    rmSync(dir, { recursive: true, force: true });
  }
});
