// `raph agents-md [--out <path>] [--stdout] [--force]` (18.6)
//
// Writes the canonical AGENTS.md so coding CLIs that read that convention from the
// repo root — Codex CLI is the proven one — get the brain without needing Raphael's
// Claude Code hooks. One file, many readers.

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { loadIndex } from '../lib/compile.js';
import { decisionsBlock, atlasDigestBlock } from '../lib/inject.js';
import { renderAgentsMd } from '../lib/agentsmd.js';

const MARKER = 'Generated by Raphael';

export default async function agentsMd(args) {
  const outFlag = args.indexOf('--out');
  const target = path.resolve(outFlag !== -1 && args[outFlag + 1] ? args[outFlag + 1] : path.join(process.cwd(), 'AGENTS.md'));
  const toStdout = args.includes('--stdout');
  const force = args.includes('--force');

  let lessons = [];
  try {
    lessons = (loadIndex().lessons ?? []).map((l) => ({
      id: l.id,
      title: l.title,
      headline: l.injection?.headline ?? l.title
    }));
  } catch {
    lessons = []; // an unbuilt brain is not an error — the file still explains itself
  }

  const body = renderAgentsMd({
    lessons,
    decisions: decisionsBlock(200),
    atlasHint: atlasDigestBlock(process.cwd(), 200)
  });

  if (toStdout) {
    process.stdout.write(body);
    return 0;
  }

  // Never silently clobber a hand-written AGENTS.md — this file is often the
  // user's own, and losing it to a generator would be unforgivable.
  if (existsSync(target) && !force) {
    const existing = readFileSync(target, 'utf8');
    if (!existing.includes(MARKER)) {
      console.error(`raph: ${target} already exists and was not written by Raphael — refusing to overwrite.`);
      console.error('      review it, then re-run with --force (or --out <path> / --stdout).');
      return 1;
    }
  }

  writeFileSync(target, body, 'utf8');
  console.log(`raph: wrote ${target}`);
  console.log(`      ${lessons.length} lesson(s) available; the file inlines the ones that fit and tells the agent how to pull the rest.`);
  console.log('      CLIs that read AGENTS.md from the repo root (e.g. codex) now get the brain with no extra setup.');
  return 0;
}
